version: '3'

services:

  db:
    container_name: db
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - /data/postgres:/data/postgres
    - ./database/1-tables.sql:/docker-entrypoint-initdb.d/1-tables.sql
    - ./database/2-data.sql:/docker-entrypoint-initdb.d/2-data.sql
    environment:
      - POSTGRES_DB=dbwms
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata

  backend:
    container_name: backend-sb
    build:
      context: backend-sb
      dockerfile: Dockerfile
    environment:
      - DB_SERVER:db
      - POSTGRES_DB=dbwms
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 8080:8080

    depends_on:
      - db
