version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - /data/postgres:/data/postgres
    - ./1-tables.sql:/docker-entrypoint-initdb.d/1-tables.sql
    - ./2-data.sql:/docker-entrypoint-initdb.d/2-data.sql
    env_file:
    - docker.env
    networks:
    - postgres
 
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres
 
networks:
  postgres:
    driver: bridge

# sudo docker ps
# sudo docker inspect CONTAINER ID | grep IPAddress
#   "IPAddress": "172.22.0.2"
# para Host de pgadmin4 crear Server
